# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: CogSci 2023 Workshop on Games
# description and keywords for meta tags
description: "2023 Cognitive Science Workshop on Video Games as a Solution to Newell's (1973) Problem of How to Create a Unified Theory of Cognition"
keywords: "video games, cognition, computational cognitive models"

# author settings for cc-by, appears in the footer
author: George Kachergis and Joe Austerweil
pub_year: 2023
github_username: kachergis

# add the full url for the github repository
repo: "https://github.com/kachergis/games4understanding"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://kachergis.github.io
url: "http://www.games4understanding.com"
# add subsection of the domain,
# on gh-pages this is /games4understanding
baseurl: ""

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google-analytics-id: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
